### ISSUE TITLE
Incorrect namespace::clean distroprefs

### ISSUE THREAD

**Issue by ribasushi** [rurban/distroprefs#3]
[None of this](https://github.com/rurban/distroprefs/blob/master/prefs/RIBASUSHI.namespace-clean.yml#L19-L24) is applicable anymore. Testing via plain tarball install confirms things to be a-ok without the distropref.

**Comment by rurban** [comment]
Yes, that's what the yml rules says also. "This distropref file has lost its right to exist but it's always
good to have a reminder that connects to a ticket"

The depends rule was applicable to 0.21, and the rest is documented as such.
I've updated the depends rule to the latest release.
