### ISSUE TITLE
Second distropref of Package::Stash::XS is not used

### ISSUE THREAD

**Issue by ribasushi** [rurban/distroprefs#4]
I am not sure why this happens and what is to blame, however [there is clear indication](https://travis-ci.org/ribasushi/dbix-class/jobs/136619596#L775-L783) the distropref is only applied half-way. The [second patch](https://github.com/rurban/distroprefs/blob/master/prefs/Package-Stash-XS.yml#L12-L16) seems to be completele ignored, and then [fails several lines down](https://travis-ci.org/ribasushi/dbix-class/jobs/136619596#L824-L831).

**Comment by rurban** [comment]
Thanks, good catch. The orig part in the 2nd patch was wrong. Fixed

**Comment by ribasushi** [comment]
Something is still wrong. I [reduced things to the simplest possible](https://github.com/ribasushi/dbix-class/blob/6bd43bd5b50f26f622ea5a910480bd4033daec36/.travis.yml#L112-L121). The [distropref is applied](https://travis-ci.org/ribasushi/dbix-class/jobs/136665381#L593-L613). Yet things [still fail](https://travis-ci.org/ribasushi/dbix-class/jobs/136665381#L1028-L1031). The harness does not respect the "verbose" envvars, so I can't give you better diag :/

**Comment by rurban** [comment]
Yes, the `t/00-compile.t` patch seems to be not good enough yet. Interesting that it did work for me, so there still seems to be -Mblib missing, looking at some pre-installed versions.

**Comment by ribasushi** [comment]
Closing in lieu of https://github.com/rurban/distroprefs/pull/5
