### ISSUE TITLE
Second prefs for EV not used

### ISSUE THREAD

**Issue by sten22** [rurban/distroprefs#8]
tested on win32 + cperl5.22.4c, cpan in debug mode:

```
...
Applying 1 patch:
  C:\cperl\cpan\sources\authors\id\R\RU\RURBAN\patches\EV-loop.patch
  "C:\Program Files\Git\usr\bin\patch.EXE" -N -p0
patching file ./EV.xs
Argument "1.5000c" isn't numeric in numeric ge (>=) at C:\cperl\lib/CPAN
/Distribution.pm line 673.
Configuring M/ML/MLEHMANN/EV-4.22.tar.gz with Makefile.PL
...
```

**Comment by sten22** [comment]
https://github.com/andk/cpanpm/blob/master/lib/CPAN/Distribution.pm#L2465

CPAN doesn't support different prefs for one perl module. We can join it in one pref with 2 patches or patch CPAN::Distributuion. What is better?

**Comment by rurban** [comment]
Join it into one. Thanks.

Am 07.09.2016 7:13 vorm. schrieb "sten22" notifications@github.com:

**Comment by rurban** [comment]
Done for several yml's. With multiple entries, it takes the first matching. But there you can do mult. patches.
